### ISSUE TITLE
Full-text search for ideas.  [2]

### ISSUE THREAD

**Issue by fisx** [liqd/aula#1001]
1. change filter & search plumbing (full text search is slightly different from sorts).
2. consider idea title, idea description ~~, comments~~.
3. add to all occurrences of the "sort ideas" menu.

**Comment by np** [comment]
The current status/plan is the following:

- [x] Add an extra field to `IdeasQuery` for the search term
- [x] Adapt paths, handlers...
- [x] Decide if a search term appears in an idea (title, desc, comments (text and replies))
- [x] Searching can be demonstrated using `?has=your+search+term`
- [ ] Extend the UI with a box and button
- [ ] Search term with multiple words should be a conjunction

**Comment by fisx** [comment]
change request: please do not search the comments.  just idea title and description.  less noise that way.

**Comment by fisx** [comment]
(i'm changing the description accordingly.)

**Comment by fisx** [comment]
all words in the search phrase should be searched in conjunction (not as a fix substring).  so "yeay go aula" should be matched by "aula go".

**Comment by fisx** [comment]
fixed in #1003.
