### ISSUE TITLE
Printable list of initial passwords  [7]

### ISSUE THREAD

**Issue by fisx** [liqd/aula#1005]
- We need a template xmlx file to start with this.
- Options are HTML or xlsx (https://hackage.haskell.org/package/xlsx) output.

**Comment by np** [comment]
If I process these issues in order this means that I will need this template soon.

**Comment by fisx** [comment]
we have a sample xslx!  (-:

[passwörter.xlsx](https://github.com/liqd/aula/files/693515/passworter.xlsx)
[passwörter.pdf](https://github.com/liqd/aula/files/693518/passworter.pdf)

The pdf is generated with libreoffice, output from other offices will probably look different.

**Comment by fisx** [comment]
Ah, just thought of something: instead of the class name in the first line, we should probably use it as the sheet name rather than "Sheet 1".
