### ISSUE TITLE
Contain login name of user who reports offensive content in the email to the moderators.

### ISSUE THREAD

**Issue by fisx** [liqd/aula#1027]
tasks:

- [x] ~~add confirmation dialog to all report forms (if it doesn't exist yet).~~
- [x] include login name and real user name in email to moderators [#1029]

text for the confirmation dialog: "Bitte schicke diese Nachricht nur ab, wenn du wirklich einen Missbrauch melden möchtest."

**Comment by fisx** [comment]
@np ping.

**Comment by fisx** [comment]
(updated confirmation dialog text.)

**Comment by np** [comment]
The reporting buttons redirect to a form to fill the reason of the report. On one of them the text is

> Hier kannst du ein Nutzerprofil wegen eines verletzenden oder anstößigen Inhalts beim Moderationsteam melden. Das Team erhält eine Benachrichtigung und wird die Idee schnellstmöglich überprüfen. Bitte gib unten einen Grund an, warum du den Inhalt für anstößig oder verletzend hältst.

This seems explicit enough. Should we add anything about the fact that reports are not anonymous?

**Comment by fisx** [comment]
> This seems explicit enough. Should we add anything about the fact that reports are not anonymous?

I've been thinking that I would never assume anonymity in this context if it's not explicitly guaranteed, and it has been edited out of the confirmation box message, so I'd say no.

**Comment by fisx** [comment]
I have the decisions from the client.

- The user is not to be told explicitly that the report feature is not anonymous.
- The CSV button should stay.  It's good to have options.

**Comment by np** [comment]
Time budget so far 1.5 hour
