### ISSUE TITLE
Render 500 Server Error Page for exceptions.

### ISSUE THREAD

**Issue by andorp** [liqd/aula#121]
Rendered 500 page should show information in the frame.

**Comment by fisx** [comment]
(This is less urgent IMO, because we already get information on 500 errors on stdout.)

**Comment by fisx** [comment]
Also, losely related: 404 shouldn't be rendered in a `Middleware`, but by a catch-all end point.  This could either be a `Raw`, or a custom combinator and `HasServer` instance.

**Comment by fisx** [comment]
also losely related: if you are not logged in, you get 404 on pages that do not exist, and 303/login on pages that do.  it should be the latter for both.

**Comment by fisx** [comment]
there was talk about a catchall handler over at servant.  not sure what the status there is, or whether it helps.
