### ISSUE TITLE
Make src/Arbitrary more generic and more pleasing to the eye.

### ISSUE THREAD

**Issue by fisx** [liqd/aula#152]
Our random (not consistent) tests data mixed binary noise with `arbWord` and `arbPhrase`, but not in a consistent way.  We should use newtypes in `src/Types.hs` more aggressively wherever we want random data to look sane in `exec/RenderHtml.hs`-generated pages, and use sop more aggressively instead of explicit calls to `arbWord` and `arbPhrase`.

**Comment by andorp** [comment]
@fisx Can we close this?
