### ISSUE TITLE
Nitpick: inconsistent capitalization (and language?) of submit buttons

### ISSUE THREAD

**Issue by Mikolaj** [liqd/aula#162]
~/r/aula$ git grep inputSubmit
src/Frontend/Page/Admin.hs:                DF.inputSubmit "AENDERUNGEN SPIECHERN"
src/Frontend/Page/Admin.hs:                DF.inputSubmit "AENDERUNGEN SPIECHERN"
src/Frontend/Page/FileUpload.hs:                DF.inputSubmit "upload!"
src/Frontend/Page/Idea.hs:                DF.inputSubmit   "Add Idea"
src/Frontend/Page/Idea.hs:                DF.inputSubmit   "Speichern"
src/Frontend/Page/Login.hs:                DF.inputSubmit   "Login"
src/Frontend/Page/Topic.hs:                DF.inputSubmit   "Add Topic"
src/Frontend/Page/Topic.hs:                DF.inputSubmit "Speichern"
src/Frontend/Page/User.hs:                DF.inputSubmit "ANDERUNGEN SPEICHERN"

The other `DF` names seem consistently English and lowercase, but you can run `git grep "DF\."` afterwards to make sure.

**Comment by andorp** [comment]
They are copied from the click-dummy.

**Comment by rittermo** [comment]
Not sure where all the different labels come from. For example, Nadine had no English labels in her clickdummy apart from “Login”. As a general rule, I would suggest that we take the German labels from Nadine’s clickdummy but only with the first letter of the first word capitalized (this first word is normally a noun in the German labels of two words). Capitalization apart from that should only happen via CSS styles later. 

If the German labels pose problems for the developers, it would be nice to have a translation file, where Nadine or me can go through and set the English labels as well as the German equivalents. In  English labels I would also capitalize the first letter of the first word only.

**Comment by fisx** [comment]
Ok, that is a good rule set, thanks @rittermo!

Trying to decide how to handle these issues, I've been thinking that we should perhaps not look at texts for now, and have somebody proof-read everything right before each alpha-release paired with a developer.

I will close this for now.  Feel free to re-open if there is anything else.

**Comment by Mikolaj** [comment]
Fair enough. See #174.
