### ISSUE TITLE
Missing static resources

### ISSUE THREAD

**Issue by fisx** [liqd/aula#187]
Two of the static resources are 404:

![2016-03-11-084442_750x789_scrot](https://cloud.githubusercontent.com/assets/10210727/13696286/bb9ec0d8-e765-11e5-813c-325b5c52d361.png)

**Comment by fisx** [comment]
this may be unrelated, but it's also interesting:

```
$ la static-src/scss/core/_reset.scss
lrwxrwxrwx 1 mf mf 60 2016-03-10 17:40 static-src/scss/core/_reset.scss -> ../../../static/third-party/HTML5-Reset/assets/css/reset.css

$ la ../../../static/third-party/HTML5-Reset/assets/css/reset.css
ls: cannot access ../../../static/third-party/HTML5-Reset/assets/css/reset.css: No such file or directory
```

**Comment by fisx** [comment]
(Sorry, the _reset.scss was an uninitialized submodule.  But the two font files are still missing / named differently.)

**Comment by local-girl** [comment]
Those paths aren't relative from the static/scss/core folder  but from the static/css
You can tell they work cause if you look at the code for _reset.scss it's full of lovely css
