### ISSUE TITLE
Reset Password Page

### ISSUE THREAD

**Issue by andorp** [liqd/aula#190]
* There is no design for the reset password page.
 * There is no exact description how the reset password should work.
 * What should happen if we reset a password for a user who has no email address?

**Comment by fisx** [comment]
![20120101_170735](https://cloud.githubusercontent.com/assets/10210727/13775334/4875d910-eaa4-11e5-8563-fddf4962f462.jpg)
![20120101_170742](https://cloud.githubusercontent.com/assets/10210727/13775338/4cf99b2a-eaa4-11e5-8073-4426224055fd.jpg)
