### ISSUE TITLE
Delete user

### ISSUE THREAD

**Issue by andorp** [liqd/aula#191]
There is a button on the edit user page, which deletes the user.

 * The user deletion behavior is not defined.
 * There are no design for the user deletion page.

**Comment by andorp** [comment]
User deletion will be a POST only request handler, which will be a new type of handler in our codebase.

**Comment by fisx** [comment]
the "delete user" is a link (get request) to a simple confirmation form ("are you sure you want to delete user X?")

option for removing the data:
1. all links in the DB (author references) are redirected to "deleted" special user.  comments stay, topics stay, delegations go away.  many other technical details to consider!
2. user is marked as "deleted"; no information (or just user name and avatar) is deleted.  note: this means that names of deleted users can't be used again.  this is good to avoid confusions.

2. is much easier to implement and even more easier to maintain.  we should at least go for this for the may deadline.

**Comment by fisx** [comment]
conclusion:

- users should be marked as deleted.
- deleted users are not visible anywhere, cannot be edited, etc.
- where authorship is visible (comments, proposals, ...), a special marker "deleted user" is shown.
- delegations: ?  (let's see what we think when we implement it.)

this needs to be signed off by the client to guarantee compliance with data protection laws.

**Comment by fisx** [comment]
this is signed off by the client:

```
Date: Thu, 7 Apr 2016 14:15:56 +0200
From: @rittermo
To: [...]
Subject: Answers from the client

[...]

3) Is it okay if we leave deleted users in the DB but show “deleted users” instead
of their username for all ideas and comments?
Yes, that’s a very good way to do it.
```
