### ISSUE TITLE
make sensei does not watch aula directory

### ISSUE THREAD

**Issue by andorp** [liqd/aula#192]
I reinstalled the docker image and, when I start sensei it does not watch the current directory. I need to restart the test suite manually. Any ideas what could have gone wrong?

**Comment by fisx** [comment]
> I reinstalled the docker image and, when I start sensei it does not watch the current directory. I need to restart the test suite manually. Any ideas what could have gone wrong?

if there are sym links that do not point to a valid file at the time of starting sensei, file watch writes a well-hidden error messages to stdout/stderr and gives up.  emacs writes such links sometimes, but i can imagine that docker volumes may trigger that issue as well (sym link is valid ouside of container, but not inside, something like that).

workaround: end sensei (^D), remove offending sym link, start again.

**Comment by fisx** [comment]
I will close this in the hope my answer worked.  Please re-open if not.
