### ISSUE TITLE
Edit Topic Page.

### ISSUE THREAD

**Issue by andorp** [liqd/aula#202]
There is a page for the `Edit Topic` in the click dummy 10.2, and the implementation has as a MoveIdeasToTopic page for the 10.2. There are separate paths defined for `EditTopic` and `MoveIdeasToTopic`. These two pages seem to be different ones.

**Comment by fisx** [comment]
where does the "gear" point to?  ("alle ideen" tab, icon in the upper left.)

**Comment by fisx** [comment]
1. we make one page that merges "edit topic" and "move ideas".
1. "create topic" and "edit topic" look very similar.
1. no overlays (for now).

**Comment by fisx** [comment]
conclusions:

- gear box is sort order pull-down menu: default="date", other option: "support".
- "create topic" link on topics overview page should go away; ideas that have reached quorum have a link in the pull-down menu.  (button can stay for now.)
- ack everything above.

**Comment by fisx** [comment]
i think this is solved.  please re-open if not.
