### ISSUE TITLE
Add demo server instructions to login page

### ISSUE THREAD

**Issue by fisx** [liqd/aula#203]
we could mention helpful details like:

- if you login as admin with any password, you can play.
- if you login as any other user, the server will crash a little.

this list could be extended with other users that we add to allow for testing different roles.

@rittermo, this is against the click dummy, but it might help.  what do you think?

**Comment by fisx** [comment]
(this isn't blocking anything, but the label will make it visible in our PO meeting tomorrow.)

**Comment by Mikolaj** [comment]
BTW, there is already user `admin2` for testing that we can actually have different users (though logging in as one logs out the other, currently).

**Comment by fisx** [comment]
inline in login page vs. make a more subtle link to separate howto page?

**Comment by fisx** [comment]
conclusion:

- add table under the fine-print directly on the login page
- somewhat unrelated: logged-out page does not exist, logout redirects to login page.
