### ISSUE TITLE
Event log

### ISSUE THREAD

**Issue by andorp** [liqd/aula#216]
* Define the event log format
 * Define combinators
 * Use event logging at errors, redirection, login, logout

**Comment by andorp** [comment]
@fisx is this implemented already?

**Comment by fisx** [comment]
not done.  the only thing we have is a user-facing event log type ("idea has been edited" and things like that, not "disk full", "database inconsistent", ...).

**Comment by fisx** [comment]
Still missing afterin #473:

```haskell
  | EventLogTopicNewPhase         topic Phase Phase
  | EventLogIdeaNewTopic          idea (Maybe topic) (Maybe topic)
```

**Comment by fisx** [comment]
(for ideas-new-topic, we should implement moving ideas first (via the `...`-menu. it may be different on the UI from editing topics.)
