### ISSUE TITLE
Refactor: Frontend.Html -> Frontend.Page.*

### ISSUE THREAD

**Issue by fisx** [liqd/aula#24]
In order to

- be able to introduce page-local names,
- keep the module size below the 2000 LOC mark,
- have an easy way of working in parallel on different pages,

I would like to propose to make the following changes:

- eliminate `Frontend.Html`
- everything used in several pages goes to `Frontend.Core`
- every type `PageX` goes to a fresh module `Frontend.Page.X`
- everybody who starts working on a page type opens a github issue and assigns it to himselves

**Comment by andorp** [comment]
I would keep `Frontend.Html` until we haven't finished every page. That way we have a progress bar.

**Comment by andorp** [comment]
I have already started to work on CreateIdea at the frontend side. PR is on the way.

**Comment by andorp** [comment]
````haskell
data ProtoIdea = ProtoIdea
    {
    , _ideaTitle      :: ST
    , _ideaDesc       :: Document
    , _ideaCategory   :: Category
    , _ideaSpace      :: IdeaSpace
    }
 
...
 
addIdea :: ProtoIdea -> Persist Idea
addIdea = addDb dbIdeas
````

**Comment by andorp** [comment]
I am closing this, as we started to use the `Frontend.Page.*` modules.

**Comment by fisx** [comment]
But `Frontend.Html` is sitll there.  I would like to keep this open until the "eliminate that module" has been resolved.

**Comment by andorp** [comment]
ok

**Comment by andorp** [comment]
There is no Frontend.Html any more.
