### ISSUE TITLE
Allow for moving ideas from topics back into the `wild idea` page

### ISSUE THREAD

**Issue by fisx** [liqd/aula#248]
(It may turn out too late that an idea should not be in a particular topic.)

**Comment by rittermo** [comment]
I think this is a very important feature and should be implemented. It will probably happen a lot that wild ideas are assigned to topics by accident. I would say this should be implemented by editing a topic and then clicking a button on an idea in the list of ideas associated with the topic to remove it from the topic. It should then move back to the wild ideas and could be re-assigned to another topic.

**Comment by fisx** [comment]
has been solved a while back.
