### ISSUE TITLE
Login error handling

### ISSUE THREAD

**Issue by fisx** [liqd/aula#258]
See discussion in #253 and FIXME in `Frontend` (added in that PR):

```haskell
       -- login / logout
       -- FIXME: login should not ask a query parameter whether or not to show a login error, but
       -- use form validation of some cookie-based message queue.
  :<|> "login" :> QueryParam "status" Bool :> FormHandler PageHomeWithLoginPrompt
```

**Comment by fisx** [comment]
potentially relevant: https://hackage.haskell.org/package/digestive-functors-0.8.0.1/docs/Text-Digestive-Form.html#v:validateM

**Comment by fisx** [comment]
has this been resolved by now?  (the FIXME from the description certainly has, just wondering if there was something else to this issue.)

**Comment by np** [comment]
This is resolved.
