### ISSUE TITLE
Delegation graph page: selection menus

### ISSUE THREAD

**Issue by fisx** [liqd/aula#293]
We have a very early prototype of the delegation graph visualization running under `/delegation/view`.  There are three columns, left to right: (1) context selection; (2) show/hide individual users in the graph; (3) the graph.  This issue is about fixing (1).

We have several context levels on which we can delegate votes: school, school class, topic, idea.  On each level except school, there are usually many sibling contexts: class 7a, 7b, 10a, ...; topic "sauna area", topic "lunch break DJs on wednesdays", ...; same for ideas.

So we need one pull-down menu for the level, and a second one that gives all the siblings based on the selection in the first.

The prototype loads a json file with test data.  This data constitutes the available siblings.  (Currently only classes or school.)

**Comment by fisx** [comment]
@local-girl ping

**Comment by local-girl** [comment]
Hi.

**Comment by fisx** [comment]
see also: #479.

**Comment by fisx** [comment]
note that all of quorum vote, votes on comments, and votes on ideas can be delegated.

**Comment by fisx** [comment]
this issue is about finding a navigation concept, but we have that on master now.  also see #690.
