### ISSUE TITLE
No more than one like/vote per user on each idea

### ISSUE THREAD

**Issue by np** [liqd/aula#308]
I've recently changed votes and likes from a `Set` to an `AMap` which keeps `addDb` as the main entry point to add records to the DB.

However I want to argue here that not having IDs for votes and likes could be even nicer. Recall that we do not want more than one like/vote per user&idea. So the votes could be indexed by user id. When one needs to point to a particular vote we can use `(ID Idea, ID User)`.

**Comment by fisx** [comment]
sounds good.

keep in mind that we will probably be changing the "database schema" sooner or later.  if we decide to have all votes in a separate table, this key would still be ok, so i think we should go ahead and do this.
