### ISSUE TITLE
Class quorum must be configurable for every class individually.

### ISSUE THREAD

**Issue by fisx** [liqd/aula#318]
currently we only have two settings: school, and "all classes".  i think that's how the click dummy does it.

**Comment by rittermo** [comment]
You’re right @fisx the quorum should only be defined for all classes and the whole school. It’s defined in percent of the users in these idea spaces anyway. The only reason for the differentiation between school-wide and all classes is, IMO, that you might want to set a higher quorum for topics that concern the whole school than for things that are only relevant to smaller groups like classes.
