### ISSUE TITLE
Dirty flag for DB data

### ISSUE THREAD

**Issue by andorp** [liqd/aula#32]
The types which have `MetaInfo` should be equipped with a `dirty` flag at type level, which shows us, if it necessary to update the data into the database. Any (pure) function which operates on the data should state its type of data usage. Like:

````haskell
data Dirt = Clean | Changed

changeTitle :: User d -> User 'Changed
changeTitle = ...

updateUser :: User Changed -> Persist (User 'Clean)
updateUser = ...
````

Another approach for this is to create a newtype.

````haskell
newtype Data u (d :: Dirt) = Data u

changeTitle :: Data User d -> Data User 'Changed
changeTitle = ...

updateUser :: Data User 'Changed -> Persist (Data User 'Clean)
updateUser = ...
````

**Comment by fisx** [comment]
Yes, good idea.  I like the second approach slightly more.  It will also make it possible to move the `MetaInfo` out of `User`, ... into `Data`.

**Comment by np** [comment]
I guess we won't need this after all. If you agree @andorp, I let you close it.
