### ISSUE TITLE
Introduce Frontend.Snippet module.

### ISSUE THREAD

**Issue by andorp** [liqd/aula#346]
The following modules are misplaced:

- `Frontend.Page.Comment`
- `Frontend.Page.Category`

These modules should have placed into a different module structure, like `Frontend.Snippet.*`

**Comment by andorp** [comment]
#335

**Comment by andorp** [comment]
The `ListItemIdea` from `Frontend.Core` should be part of some snipplet module.

**Comment by fisx** [comment]
@andorp this can be closed, right?  I'm closing it, please re-open if not.

**Comment by andorp** [comment]
Implemented in #383
