### ISSUE TITLE
Script that checks formatting

### ISSUE THREAD

**Issue by andorp** [liqd/aula#361]
Lets formalize the extra line commando / whitespace police :)

**Comment by fisx** [comment]
yes, but github issues have a running cost because we need to look at them regularly, and i would say this task is not important enough to justify that cost.  what do you think?

i am happy to try and stop making so much noise editing whitespace if you would like!  just say the word!  (-:

**Comment by andorp** [comment]
I am ok with you adding whitespace changes. Also I am ok, if we check the code from time to time fo fix these whitespaces in a PR.
