### ISSUE TITLE
JavaScript <-> Haskell interface.

### ISSUE THREAD

**Issue by andorp** [liqd/aula#363]
At least the following function names are shared functionality between Haskell and JS:
 * `handleDeleteComment`
 * `handleLikeOrVote`

Can we define these names somehow in a unified way?

**Comment by fisx** [comment]
how are the names not unified?  can you make a suggestion?

**Comment by andorp** [comment]
We have these names as 'random' strings in the JavaScript code, and in the Haskell code. If they are changed only one side, we can't have a method to test them. One solution for this, is a script which checks if the function is defined in JS which we call from Haskell. Other suggestions are more than welcome. :)

**Comment by fisx** [comment]
> We have these names as 'random' strings in the JavaScript code, and in the Haskell code. If they are changed only one side, we can't have a method to test them. One solution for this, is a script which checks if the function is defined in JS which we call from Haskell. Other suggestions are more than welcome. :)

my suggestion would be to close this issue and work on test coverage and selenium testing.  once we have that under control, there will be a test for each js function that triggering a call to it, and we will catch all inconsistent name changes.  and many other issues.

there are other ways that help a little, like what you suggest, but they also complicate things a lot.

**Comment by andorp** [comment]
Until we have only 2 of these, they are manageble. When an issue comes from this double bookkeeping we need to think a solution.
