### ISSUE TITLE
status messages hide `...` menu

### ISSUE THREAD

**Issue by fisx** [liqd/aula#482]
to reproduce:

- login as admin
- move to any topic
- select `...` -> `move to next phase`
- try to select `...`

you will have to click away the status message first, then the `...`-menu appears.

i also find it still hard to operate this menu.  not sure how to be more specific here.  i just feel clumsier than usual when i try to use it.  (-:

**Comment by localgrr** [comment]
I agree it's slightly clumsy but not gonna address it until more people bring it up as I fear it might be tricky
