### ISSUE TITLE
Move ideas to topic

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#486]
https://marvelapp.com/ehhb43#10224351

**Comment by fisx** [comment]
So the page works like "edit topic", except it does not have fields title, description, and it doesn't let you select ideas, but topics.

**Comment by fisx** [comment]
@rittermo: can this be done by student?  or just by moderator?

**Comment by andorp** [comment]
As agreed with customer we are not doing overlays. This function will be implemented as a new page.

**Comment by rittermo** [comment]
Should be only done by moderators
