### ISSUE TITLE
Create, edit topic: idea lists for moving into new topic.

### ISSUE THREAD

**Issue by fisx** [liqd/aula#489]
current behavior (6f117148):

- when creating a topic, there only the wild ideas that have reached the quorum are listed.
- when editing a topic, all wild ideas and all ideas previously in the topic are listed

what we want (@rittermo, can you confirm this?):

- empty list should contain the text "Es stehen keine Ideen zur Auswahl."
- the idea list should always include the wild ideas that have not reached the quorum
- all ideas should be marked with the information whether they reached the quorum or not.

**Comment by rittermo** [comment]
Works for me!

**Comment by rittermo** [comment]
Looks and works great!

**Comment by rittermo** [comment]
Looks and works great!
