### ISSUE TITLE
Show idea category in the idea list

### ISSUE THREAD

**Issue by fisx** [liqd/aula#498]
- both in wild idea lists and it list of ideas in topic.
- only show icon.
- find a nice place (perhaps next to the author with the same height as the author?

**Comment by rittermo** [comment]
Hey @localgrr, the icon placement looks great. Unfortunately, the label (text) of the category overlaps with the title. After some testing, I think we could get rid of the label altogether and  just display the icon.

<img width="1184" alt="bildschirmfoto 2016-05-21 um 09 35 22" src="https://cloud.githubusercontent.com/assets/15341015/15447150/bccabb38-1f37-11e6-83d8-ae7c7eb53e7e.png">
