### ISSUE TITLE
Ideas must not be editable in jury phase or later.

### ISSUE THREAD

**Issue by fisx** [liqd/aula#501]
but they are.

**Comment by rittermo** [comment]
Just a heads up: The creator statement of an idea must still be editable after the voting phase!

**Comment by andorp** [comment]
This is about the editing of the title and a description of the idea.

**Comment by andorp** [comment]
The handling of the creator statement is not changed with the #505.

**Comment by andorp** [comment]
@rittermo Thanks for the heads up :)
