### ISSUE TITLE
Better display of form validation errors

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#502]
Currently validation errors are displayed very bleakly at the beginning of the form. This should be changed to either 

a) (The nicest version in terms of UX Design) Display the validation error next to form field that is concerned and make them and the form field stand out visually by adding a red color for the text and possibly a red border for the form field.

b) (Probably the easier solution but not so nice in terms of UX) Display a list of validation errors at the beginning of the form as a list in red color and give the list a label/headline like “Es traten folgende Fehler in den Eingaben auf:”

**Comment by fisx** [comment]
to test:
- login as admin
- prozessverwaltung
- quorums
- enter a number > 100

the code:
https://github.com/liqd/aula/blob/32ad25134cd13c33fb0cd3a98cbf77dcabd59e99/src/Frontend/Core.hs#L335
