### ISSUE TITLE
Enable markdown for idea description

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#503]
Currently in v0.11.3 line breaks and markdown is not parsed in the idea description (see: https://thentos-dev-frontend1.liqd.net/space/2016-10a/idea/3003/view) 

Did we disable it intentionally? Should definitely be enabled for Monday, May 23, even if some formatting looks strange.

---

Original text from client:
Ideenbeschreibung zeigt Linebreaks als Spaces an. Längere, strukturierte Beschreibungen werden so zu einem Textschwall.

**Comment by fisx** [comment]
related #469.

**Comment by fisx** [comment]
I accidentally disabled it on the server.  Will be fixed in the next release.

**Comment by fisx** [comment]
I fixed staging2 and the taiga wiki deployment instructions.  So this specific mistake shouldn't happen again in the future.
