### ISSUE TITLE
Do not show jury statement in topic overview

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#508]
Jury phase: The jury statement text should not be shown on the topic overview but only on the idea detail page (see here: https://marvelapp.com/ehhb43#10141314 and here https://marvelapp.com/ehhb43#10108432) [FIXED in v0.7.0, needs design tweaking; the jury statement is still shown in the list view in v0.7.0 @cc?]

**Comment by fisx** [comment]
so we show a simple verdict, not the comment included in some verdicts.

the verdict still has the wrong look, though.  it's a text instead of a symbol, and it's in the wrong place.  @localgrr i think you may be able to do this; please assign to one of us if you need the app logic to change.

**Comment by fisx** [comment]
closed in #510.
