### ISSUE TITLE
Voting phase needs clarification

### ISSUE THREAD

**Issue by fisx** [liqd/aula#512]
1. in voting phase and result phase, votes should be sorted by support.  however, support is not defined based on quorum votes (aka likes) any more, but on votes.  there is a function that gives a number to the support of an idea based on numbers of yes votes, no votes, and voters, resp.  a first shot at this function could be `#yes / #no`
1. what should the final function be here?
1. is "mark as winner" going away entirely?
1. can creator's statements be entered for non-winning ideas?

**Comment by rittermo** [comment]
Alexa will clarify this with Marine and we’ll get feedback via email in the next days.

**Comment by fisx** [comment]
(see poldi pad)

**Comment by fisx** [comment]
Marina:

>  Die Ideen sollten in der Tat in einer Reihenfolge stehen. Sie sollten eingeteilt sein in angenommene Ideen und nicht angenommene Ideen. Angenommene Ideen müssen mehr positive als negative Stimmen haben und müssen ein Minimum an 30% der gesamten Stimmen erhalten. (Wenn eine Klasse also 30 SchülerInnen hat, müssen mindestens 10 abgestimmt haben, davon mindestens 6 dafür). Alternativ - und hier baue ich auch auf eure Meinung - kann man das Quorum bei 30% POSITIVEN Stimmen ansetzen (Bei einer Klasse mit 30 SchülerInnen müssen also mindestens 10 dafür gestimmt haben, und maximal 9 dürfen dagegen gestimmt haben).
>
> Die Reihenfolge der Ideen, die das Quorum passiert haben, kann sich aus der absoluten Differenz der positiven und negativen Stimmen ergeben.
> 
> Angenommene Ideen sind nicht automatisch Gewinner. Wenn eine angenommene Idee mit einer beliebteren Idee konkurriert, wird sie dennoch nicht umgesetzt. Hier finde ich es sinnvoll, wenn Moderatoren Gewinner von Hand auszeichnen können.
