### ISSUE TITLE
Make new idea button bigger

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#518]
The new idea button on the topic overview for wild ideas needs to be bigger (as big as in the clickdummy).

<img width="1346" alt="bildschirmfoto 2016-05-18 um 13 31 37" src="https://cloud.githubusercontent.com/assets/15341015/15357110/18a2956c-1cfd-11e6-9bd2-7612620dddeb.png">

**Comment by localgrr** [comment]
Fixed with https://github.com/liqd/aula/pull/525
