### ISSUE TITLE
Display comment action buttons in one line and same size

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#520]
Moderators: The buttons underneath a comment for report, delete and edit should be in one line, not underneath each other, and have the same size.

To see it, log in as moderator and view any comment on an idea detail page.

<img width="985" alt="bildschirmfoto 2016-05-18 um 13 44 02" src="https://cloud.githubusercontent.com/assets/15341015/15357381/c13f2f86-1cfe-11e6-9948-c6408c8b284c.png">

**Comment by fisx** [comment]
Fixed in v0.13.0:
![2016-05-18-140030_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/15357743/d59f90f4-1d00-11e6-9765-f4bf723eb88c.png)

@localgrr the font sizes are still different.  @rittermo should this be fixed, or is the version as is ok?

**Comment by rittermo** [comment]
I would like the font-size to be fixed, too. I would suggest the font-size of “Antworten” is fine as a standard.
