### ISSUE TITLE
Voting buttons should indicate state more nicely

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#522]
When you vote for or against an idea, the button currently shows how you voted but it‘s not very pretty. I would like to implement the design of the clickdummy (see here: https://marvelapp.com/ehhb43#10163580)

<img width="1440" alt="bildschirmfoto 2016-05-18 um 13 58 44" src="https://cloud.githubusercontent.com/assets/15341015/15357734/c639d6b0-1d00-11e6-93c0-7be87d107974.png">

**Comment by localgrr** [comment]
How do I get voting buttons again ? Sorry I tried !

**Comment by fisx** [comment]
https://github.com/liqd/aula/blob/fa95d7a7045cc92f7bf39a5f3b4289acfe757c48/src/Frontend/Page/Idea.hs#L361

The difference in classes (`btn` vs. `btn-cta`) is probably an accident, but I suspect there are other things you want to change (`m-active` or something similar)?

**Comment by fisx** [comment]
scratch my last comment, except for the link.  the two cases of `voteButton` are "selected" and "not selected", in that order.

**Comment by fisx** [comment]
(not sure if any of that answers your question?)

**Comment by rittermo** [comment]
Much better now! Yay!
