### ISSUE TITLE
All messages look like errors

### ISSUE THREAD

**Issue by localgrr** [liqd/aula#548]
Red background on user messages is a bit harsh and looks like you did something wrong. Maybe make a green one too

**Comment by fisx** [comment]
:+1:

green is a good default.  I'm not sure if we have any errors right now, but it would be nice to support yellow and red.  @localgrr if you find any place where non-green would be better, please pass me an incomplete PR so I can change the haskell message type accordingly?  if green is fine everywhere, we can also do that when the need arises.

**Comment by localgrr** [comment]
basically just add the class `m-error` if you want it red otherwise it'll be green
