### ISSUE TITLE
Do not show quorum vote button (aka like button) if quorum has been reached.

### ISSUE THREAD

**Issue by fisx** [liqd/aula#558]
this is in votes bar fragment.

**Comment by andorp** [comment]
We agreed with @fisx that would limit the number of likes for an idea, and we can not distinguish between good and great ideas.

**Comment by fisx** [comment]
Since #567, we have all-powerful admins, and all-power looks like this:

![2016-05-24-162437_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/15507475/0e1e67c8-21cc-11e6-97e3-163cc51f1fbd.png)

This exposes two small wording questions that I would like to resolve before closing this issue:

1. the upper button labeled "idee kann auf den tisch" should be rephrased if the idea is already on the table.
1. the lower button labeled "kann auf den tisch" should be rephrased to "Thema anlegen".  it's confusing that the two buttons that do so different things have so similar labels, even though moderators and students will never see both.  (actually, scratch that, i think moderators will see both.)

**Comment by rittermo** [comment]
I agree to change the label of "kann auf den tisch" to "Thema anlegen"

**Comment by fisx** [comment]
so let's change this one wording and close this issue.
