### ISSUE TITLE
`...` menu is not visible on cell phones and pads.

### ISSUE THREAD

**Issue by fisx** [liqd/aula#576]

**Comment by fisx** [comment]
actually, this may be a mis-reporting.  i just realized that i might have tried to find it on a topic detail view page, not an idea detail view page.  could somebody with a cell phone confirm that this can be close, and close it?  thanks/sorry!

**Comment by fisx** [comment]
not a mis-report, but most likely related to caps mis-configuration.  (to clarify: there is a `...` menu in both idea and topic detail view pages.  this grayed-out stuff really *would* be nice.)

**Comment by localgrr** [comment]
Sorry this isn't clear to me...

**Comment by fisx** [comment]
i think this is a duplicate of #734 (or vice versa), and not actually related to the device, but to the caps.  and that there is nothing wrong with the caps any more.

since this issue does not say how to reproduce it, i will close it.
