### ISSUE TITLE
Better UI solution for admin interface menu on mobile

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#587]
The menu to switch between sections in the admin interface needs a better solution to be clickable and more structured on mobile devices. Level 1 and two need to be clearly distunguished and clickable/tappable. Maybe the solution is having a second burger icon menu like for the first level items or a dropdown menu with two levels extending the dropdowns we use for sorting?   (checked on FF Responsive Design; 320x480 and on Mobile Safari v.9.3.2)
![bildschirmfoto am 2016-05-26 um 18 21 09](https://cloud.githubusercontent.com/assets/15341015/15582001/208055ee-236f-11e6-9d16-ef5bdd45e55f.png)

**Comment by rittermo** [comment]
Maybe we also could say that the admin interface is not responsive at all. There is also so much other stuff in the admin interface that would have to re-worked (like tables! ugh!) for mobile use. It might be reasonable to say that we do not make it responsive after all. We would just need to remove the responsive meta tag for the admin interface pages and users who really need to use it on their mobile phones can zoom in and out of the elements. Let me know what you think, @localgrr

**Comment by localgrr** [comment]
That's fine by me @fix could you set an if statement for meta added a fixme in ```2016-06-cc-more-bugfixes```

**Comment by fisx** [comment]
@localgrr yes, i can take a look, even though you pinged the wrong @fisx.  (hey fix, interesting stuff! :-)

where can i find that branch?

**Comment by localgrr** [comment]
@fisx pushed now

**Comment by localgrr** [comment]
PS this only works on an actual mobile device not reduced desktop screen size

**Comment by fix** [comment]
hey, somebody is fixing something somewhere on github. Just to let you know :)

**Comment by fisx** [comment]
@fix sorry for the noise (-:  cheers~

**Comment by fix** [comment]
No offense. I should have choosen another nick.

**Comment by localgrr** [comment]
Oops my bad :D

**Comment by localgrr** [comment]
@rittermo  all good ?
