### ISSUE TITLE
NTH: Show which ideas have reached the quorum in Create topic

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#596]
Create topic: Show which ideas have reached the quorum on the create topic page next to the idea in the list. This is nice to have but I think it could be a great improvement in the long run.

**Comment by fisx** [comment]
i think this has been done a while back?

**Comment by fisx** [comment]
yes, it's resolved:


![2016-06-20-102251_1920x1080_scrot](https://cloud.githubusercontent.com/assets/10210727/16187514/fef2d292-36d0-11e6-982a-c4b4bd7a85d7.png)
