### ISSUE TITLE
User role and user’s class not shown in profile

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#600]
The user’s assigned class is currently not visible on the user profile. It would be great if we could also show the user’s role like “Moderator” in the same line, if the user is not a student. 
See here, for an example: https://aula-stage.liqd.net/user/6/ideas

**Comment by fisx** [comment]
note there are potentially many roles per user now.

**Comment by fisx** [comment]
related to the delegation issues: #682, #652, #651.

**Comment by fisx** [comment]
Fixed in #699:

![2016-06-21-155942_1920x1080_scrot](https://cloud.githubusercontent.com/assets/10210727/16232042/361ecb56-37c9-11e6-9da7-61a584c0edc0.png)
