### ISSUE TITLE
Show upload constraints in upload form

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#601]
User Profile – edit profile: The size limit and file format constraints for uploading pictures are not given on the form. We should add them underneath the upload button.

A NTH: There could be a preview of the current profile pic (if there is any) left of the upload field for the new pic

**Comment by fisx** [comment]
i'm also not sure if we do have reasonable constraints in place to begin with, this needs to be checked and done if necessary.  we don't need it in Config, constants in the source are fine.

related: #436.

**Comment by fisx** [comment]
if the NTH preview button is non-negligiible extra work, we should open a new issue and move that to it.3

**Comment by fisx** [comment]
so, constraints to consider are:

- max byte size
- must be square (with an error of N%, with default 10)

i don't think we need to have min or max pixel limit, as we want to scale the image anyway.

**Comment by np** [comment]
The squareness should only be a recommendation.
The simplest way to enforce a max byte size would be at a proxy level if we have some reverse proxy in place.

**Comment by fisx** [comment]
agreed with the "recommendation".  (a flat rectangle will just loose more information during clipping, correct?)

we will probably have nginx in place.  i'm assuming it can be configured there?  still would be nice to have a middleware do it, then it would be easier to change in one place and have UI info and actual behavior agree with each other.

**Comment by fisx** [comment]
(re. the latter, i would just add a middleware to the ones we already have at the bottom of Frontend.hs.)

**Comment by fisx** [comment]
there is also a newly introduced constraint hidden here:

https://github.com/liqd/aula/blob/5866cc9135d7640360ea9587388837e7673b5390/src/Data/Avatar.hs#L99

how can that be expressed in simple english?

**Comment by np** [comment]
Ah sorry this should not be a TODO anymore it is actually impossible to reach from makeAvatar since the image is made square before that.

**Comment by fisx** [comment]
things left to do:

- we support all formats that juicy pixels supports, so no need to mention that.
- max byte size should be a constant and verified in a middle-ware.
- recommendation: high enough definition (max $ defaultSize : altSizes)
- recommendation: square ratio, circle
- preview: open separate issue, move  to it.3

**Comment by np** [comment]
We finally decided against the middleware in favor of a simple config in nginx.
A deployment document PR #747 should be in sync with the requirements.
