### ISSUE TITLE
Reset password: Send email

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#605]
Admin settings: Manage groups & users – edit user: The new password should be sent via email – if there is an address associated with the user.

**Comment by fisx** [comment]
related: #574, #642

**Comment by fisx** [comment]
(more importantly, if the user has an email address, she should be able to reset her password without involvement of an admin.  saves a lot of pain for admins.)

**Comment by fisx** [comment]
needs discussion.  i think we should just allow for request a reset email, and allow admins to change passwords without involving emails.  this extra email confuses the two things.

**Comment by fisx** [comment]
conclusion: we should send out a notification email that does not contain the password.  it just says what happened.
