### ISSUE TITLE
Interaction buttons in list view/topic overview

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#606]
Why did we implement buttons for voting and marking ideas feasible/non-feasible in the list view of ideas (topic overview)? I did not want this and Marina agreed in the pad: https://pad.liqd.net/p/aula_beta_feedback

**Comment by fisx** [comment]
we didn't implement that, but used a widget from the detail view page and may have neglected to switch it off.  however, i can't find what you mean: in the topic in class 7v, i can't see any buttons.

@rittermo: please re-open with more info if you can still reproduce this on v0.17.0 or later.

![2016-06-21-171739_1920x1080_scrot](https://cloud.githubusercontent.com/assets/10210727/16235156/2120b768-37d4-11e6-911e-8697c6626f82.png)
