### ISSUE TITLE
"mark as winning" is confusing.

### ISSUE THREAD

**Issue by fisx** [liqd/aula#608]
- idea detail view:
    - should show a winning badge.
    - *under* the badge (whether it's there or not), there should be a toggle button
    - the toggle button should read "gewinnen lassen!" (mark as winning) and "nicht gewinnen lassen!" (unmark), resp.
- topic overview:
    - ideas in list should show a winning badge if they have one.  (they already show lots of "badges".)

**Comment by fisx** [comment]
The current situation is close to the one I'd like to have, but the badge looks like a button, and it's in the wrong place:

![2016-05-30-085123_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/15641853/e5b2f124-2643-11e6-854d-a91323af7773.png)
![2016-05-30-085126_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/15641856/e820f708-2643-11e6-887b-e8b08d820fe7.png)

...  and it doesn't show in the idea list:

![2016-05-30-085155_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/15641868/f7c2ae86-2643-11e6-8ac3-42be2096da32.png)

**Comment by localgrr** [comment]
Is there any design for badges as far as we know ?

**Comment by rittermo** [comment]
The clickdummy also shows this button-style badge. I would suggest, we differentiate between buttons and badges by making badges have a white background instead of the green and a 3px outline in green as well as green text. The next time I speak to Nadine, I’ll ask her about it.

<img width="1017" alt="bildschirmfoto 2016-06-08 um 12 41 37" src="https://cloud.githubusercontent.com/assets/15341015/15891750/63353b1e-2d76-11e6-8fa0-086acf962951.png">

**Comment by localgrr** [comment]
@fisx My plan is to make this badge  parth of the icon lists EG next to durschfurbar, can you make that so ?

**Comment by localgrr** [comment]
awaiting an image from Nadine

**Comment by fisx** [comment]
@localgrr can you use a dummy image for now, and open an issue for replacing it once we have the real one?  you wouldn't have to be around for that to happen, then.

**Comment by localgrr** [comment]
@fisx  dummy image in place, Nadine is making a real image

**Comment by rittermo** [comment]
We will implement an icon with a label for when voting has ended but idea was not marked as winning.
I will ask Nadine to provide an icon for that.

**Comment by rittermo** [comment]
The icon can be found here: #860

**Comment by localgrr** [comment]
What's the actual winners icon ?

**Comment by localgrr** [comment]
ok @fisx please see 2016-07-cc-winners-icon just needs your logic, see the FIXME in idea.hs
