### ISSUE TITLE
forms still have safari mobile standard design

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#616]
[mobile] The form elements still have a standard mobile Safari styling in iOS browsers which makes the elements clash with  design (Rounded corners, no outline etc.)
![img_0069](https://cloud.githubusercontent.com/assets/15341015/15814372/9c875020-2bc6-11e6-80d2-6a3cbe374bce.PNG)

**Comment by localgrr** [comment]
I dont have IOS to test this - just tried something I read on StackOverflow
