### ISSUE TITLE
User delegation rendering should contain all delegatees below a level.

### ISSUE THREAD

**Issue by andorp** [liqd/aula#638]
Issue:
Student in class 1a, and many of her classmates delegated votes only on topic levels, the user profile page for the given user would show 0 delegation, but her real voting power is the whole class.

Reason:
~~On use profile page (https://marvelapp.com/ehhb43#10165918) : The user can see only the explicit delegates of classes and school. Which gives its a false information about the delegation power that the user have.~~

**Comment by fisx** [comment]
:+1:

also, if we have students that are in more than one class, we want to select one of the classes they share with us.

so i think the best way to solve this is to come up with a nice DScope navigation widget for the delegation network browser, and then recycle that widget here.

**Comment by fisx** [comment]
user profile now shows all delegations.

**Comment by fisx** [comment]
issue does not apply any more.
