### ISSUE TITLE
Show delegated votes

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#652]
We need a solution that indicates if I already have delegated my vote to a particular user. 

Nadine designed a solution for the user profile, which shows the delegations already made in the dropdown and a little icon next to the user name, which shows the delegations on click.

![8 1 user profile delegate_02](https://cloud.githubusercontent.com/assets/15341015/16007029/83d7bc54-3170-11e6-90ef-e183708caed8.jpg)

This is somewhat dependent on the solutions we chose in #651

**Comment by fisx** [comment]
related: #682

**Comment by fisx** [comment]
Fixed in #699.  The "delegate" buttons are now toggles, and they read "withdraw" if a delegation is active.

@rittermo please re-open if you are unhappy with this solution.
