### ISSUE TITLE
User menu is placed incorrectly.

### ISSUE THREAD

**Issue by andorp** [liqd/aula#653]
![2016-06-13-160318_1600x900_scrot](https://cloud.githubusercontent.com/assets/3465327/16010229/85cc481c-3180-11e6-98ec-42e53664e4d1.png)

Git hash: https://github.com/liqd/aula/commit/cf06b8fc404bb9c8ae2ea6274aa3d4264f177087

**Comment by localgrr** [comment]
@andorp I can't reproduce this, what browser are you using ?

**Comment by andorp** [comment]
I think it is an old one, it does not appear on my machine any more. Closing...
