### ISSUE TITLE
Use `MonadIO` instead of `ActionIO`?

### ISSUE THREAD

**Issue by fisx** [liqd/aula#67]
https://github.com/liqd/aula/commit/a4d695a7799d9e1b3193e20a881b73f373453116

I introduced that in #55, but @andorp has objections and has reverted it.

What are the pros and cons for each?  I like `MonadIO` because it is isomorphic and because I can't think of any reason to duplicate its structure.  But I'm sure there is at least one.

**Comment by andorp** [comment]
In my opinion the ActionM should be our only abstraction point where we describe what a user is able to do in the system. It is a focal point where all the other parts can be joined.

With MonadIO we say, do any IO computation whatever you want. This is not an intended behaviour of the client codes for the ActionM. Introducing ActionIO we will able to distinguish client codes which contains temporary hacks. We should authenticate and authorize every user action which is generated by the Handlers from the given http requests.

So ActionIO is the way you say, I am cheating here and it should be removed, at the end of the contruction phase. It is like a scaffolding that helps us build the house, but is is going to be removed easily after the contruction. From this point of view is not isomorphic to MonadIO (maybe a right adjoint)

**Comment by fisx** [comment]
I think I understand all this, but isn't it besides the point?

`ActionIO` is just a name, and I don't see any reason why we shouldn't use `MonadIO` to mark scaffolding that is later to be removed.

If it's really just about using a name that marks more clearly that this should be refactored, then `ActionIO` isn't ideal either.  Then I would chose `ForTestingOnlyMonadIO`.

Just to make sure I don't get you wrong: is your intention to remove `ActionIO` entirely before we go to production (I think so), or will it just change its internals?

**Comment by andorp** [comment]
> `ActionIO` is just a name, and I don't see any reason why we shouldn't use `MonadIO` to mark scaffolding that is later to be removed. 

I think we need a clear distinction. Before `ActionM` we started to use `liftIO` everywhere e.g when we needed to access persistent. This for me a bad practice. As Refactoring to Action I made and found two bugs. And type system had no objections at all, I found the bugs via manual testing and costed 1 hour to figure out what went wrong. The root cause was the usage `liftIO`.

> If it's really just about using a name that marks more clearly that this should be refactored, then `ActionIO` isn't ideal either. Then I would chose `ForTestingOnlyMonadIO`.

You are right. But As we use only in `createRandom` we should rethink the createRandom idea. Maybe to move the `generate arbitrary` to Action, and remove `ActionIO`.

> Just to make sure I don't get you wrong: is your intention to remove `ActionIO` entirely before we go to production (I think so), or will it just change its internals?

Yes

**Comment by fisx** [comment]
> > Just to make sure I don't get you wrong: is your intention to remove `ActionIO` entirely before we go to production (I think so), or will it just change its internals?
>
> Yes

I should have known better than to ask a logician a 'A or B' question.  I will assume you mean "yes, the former".  (-:

I think this all makes sense now.  I like the idea of taking `generate arbitrary` into the `ActionIO`, perhaps giving it a better name, and then not allow for any other `liftIO` anywhere outside of `Action`.

**Comment by Mikolaj** [comment]
+1 on making `generate arbitrary` a primitive of ActionM and sealing it off. Extending the set of primitives is relatively safe --- we explicitly allow stuff, even if (temporarily) we allow lots of stuff. OTOH, adding extra generic constraints is implicit and so very dangerous.
