### ISSUE TITLE
MultiUser can Report itself on the User Profile page.

### ISSUE THREAD

**Issue by andorp** [liqd/aula#678]
See attached screenshot with user `fazg`

![2016-06-17-122934_1600x900_scrot](https://cloud.githubusercontent.com/assets/3465327/16148094/9ccdb9ec-3487-11e6-95b3-b4ef05fdb33a.png)

![2016-06-17-123024_1600x900_scrot](https://cloud.githubusercontent.com/assets/3465327/16148100/a025eefc-3487-11e6-8dd4-a1b52f61d413.png)

**Comment by fisx** [comment]
this may happen to students with several classes.  some multiple-personalities thing where a student that has a class A can report on all students that have a class other than A.

**Comment by fisx** [comment]
(this is meant by the term "MultiUser" in the title :-)

**Comment by fisx** [comment]
this will be resolved with #828.

**Comment by andorp** [comment]
I would have this opened till we resolve it.
