### ISSUE TITLE
Create topic: Less indentation for idea list

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#683]
The list of ideas to be added to a new topic should not be indented on screens smaller than a width of 640px. 

The idea title needs some padding from the checkbox to the left.

https://aula-stage1.liqd.net/space/2016-6b/topic/create

![bildschirmfoto am 2016-06-19 um 21 57 40](https://cloud.githubusercontent.com/assets/15341015/16179531/2907f428-3658-11e6-9137-9ee64620c388.png)

**Comment by fisx** [comment]
Fixed in #709
