### ISSUE TITLE
Handle missing trailing slashes better.

### ISSUE THREAD

**Issue by fisx** [liqd/aula#70]
`serveDirectory` expects its path to have a trailing slash, or the relative references it lists won't work.

```
16:33 < fisx_> so, if you are on page /samples, then your working directory is /
16:33 < fisx_> then relative link x.html points to /x.html
16:33 < fisx_> if you are on page /samples/
16:34 < fisx_> then your working directory is /samples
16:34 < fisx_> then it works.
16:34 < fisx_> it's not nice, but it's not clear to me how to handle this better either.
16:35 < fisx_> perhaps if we offer "samples" :> "index.html", but not "samples"?
16:35 < fisx_> no redirect or anything?
16:35 < fisx_> (the redirect hack would make sure that nobody ever clicks a link from /samples,
16:35 < fisx_> while the url would still get everybody to /samples/, where they can be happy.
16:36 < fisx_> i've actually seen this on well-made pages before.
16:36 < fisx_> if you don't add a trailing slash, it is added for you.
16:36 < fisx_> prehaps there is even a middleware for that?
16:36 < fisx_> i'll open an issue.
```

I like the idea of adding a middleware, and letting servant work on the assumption that all urls have a trailing slash in the path.  Not sure though if I'm missing something here.

**Comment by andorp** [comment]
It won't work if the `http://localhost:8080/samples` is used instead of `http://localhost:8080/samples/` (screaming silently)

**Comment by fisx** [comment]
Our best course of action may be to call wai-app-static's `serveDirectory` instead of servant's.  This would both fix the `/` issue and allow us to eliminate `Frontend.Core.aulaTweaks`.

- https://hackage.haskell.org/package/wai-app-static-3.1.4.1/docs/Network-Wai-Application-Static.html#v:ssRedirectToIndex
- https://hackage.haskell.org/package/wai-app-static-3.1.4.1/docs/Network-Wai-Application-Static.html#v:ssGetMimeType

**Comment by Mikolaj** [comment]
Re `aulaTweaks`, its haddock suggests wai's MIME handling is not perfect (it doesn't guess "charset=utf8"), so `aulaTweaks` will probably stay. No idea, if explicit call to `ssGetMimeType` would help. Will test.
