### ISSUE TITLE
race condition in image upload

### ISSUE THREAD

**Issue by fisx** [liqd/aula#707]
The new image sometime does not appear after the upload, but on refresh it appears.

**Comment by fisx** [comment]
related: #436.

**Comment by np** [comment]
I'm not sure if this is a form of caching or not. If this is a caching issue we can add a query parameter with the timestamp or the hash of image.

**Comment by np** [comment]
We can't reproduce it anymore.

**Comment by fisx** [comment]
irc::

> 15:32 < npou> damn, I got the race condition just now while uploading my profile pic

**Comment by fisx** [comment]
It is *possible* that this has been resolved in #920, but in order to prove that we should:

1. remove the `disableCaching` middleware.
1. reproduce the issue in a test case.
1. add `disableCaching` again and confirm that the issue is gone.

**Comment by andorp** [comment]
We can not reproduce this with the test suite. There is no hard evidence how this happen. We reenable caching for the service to save energy. @fisx has an idea how to invalidate cache on the client side. Closing for now.

**Comment by fisx** [comment]
related?:

- http://stackoverflow.com/questions/174348/will-web-browsers-cache-content-over-https
- http://stackoverflow.com/questions/8155064/how-to-programmatically-empty-browser-cache
- http://stackoverflow.com/questions/1011605/clear-the-cache-in-javascript
