### ISSUE TITLE
Stimme beauftragen issue

### ISSUE THREAD

**Issue by localgrr** [liqd/aula#711]
"delegation" is visible for moderator on idea detail view in result phase.

1. moderators should never delegate or vote, or quorum-vote.  (right?)
1. delegation buttons should disappear from topic and idea view in result phase.

![1466609161447screensave](https://cloud.githubusercontent.com/assets/701632/16272556/7e40049c-389e-11e6-909c-199fb4385f2e.png)

**Comment by fisx** [comment]
can't reproduce this any more.  either we made a mistake there and `Namsea` had some other role than moderator, or it has been resolved since then.
