### ISSUE TITLE
Allow for withdrawing delegations on topic level and idea level.

### ISSUE THREAD

**Issue by fisx** [liqd/aula#730]
It's mostly there, except for this:

https://github.com/liqd/aula/pull/727/commits/4fbc6321932166e41a887eb15ffc48ce87a273ae

we need to either lookup the previous delegate (which seems a bit silly to me), or not require it for delegation withdrawal.

**Comment by fisx** [comment]
is this fixed?

**Comment by andorp** [comment]
We can withdraw delegation unselecting delegate on the `Delegate Vote` page. The text says: "DU KANNST DEINE BEAUFTRAGUNG WIDERRUFEN, INDEM DU SIE NOCHMAL ANKLICKST."
