### ISSUE TITLE
Topic overview page: mobile optimization 

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#748]
The topic overview page with all its tabs can look a bit messy on mobile screens (FF Responsive, 320x480):

<img width="331" alt="bildschirmfoto 2016-06-13 um 09 22 02" src="https://cloud.githubusercontent.com/assets/15341015/16376354/1aa8cbce-3c60-11e6-93cc-8a8299dd4225.png">

I have asked Nadine for a solution and she designed a new view with three main differences:

1. the header image is not shown anymore on smaller screens
2. there are scrollable tabs
3. the system messages have a different design (I am not sure about the color, though, maybe we should leave the color in green)

Things that I would not like to implement from Nadine’s design:

1. She didn’t show the label for the phase with its name and duration,(„Ausarbeitungsphase, endet….“) This is the one element that is hard to design around. Maybe there are some options to shorten the text there, @fisx?
2. I would not like to change the main navigation.
3. I would suggest we keep the smaller size for the topic title, as it is right now.

I am not quite sure when we should use this more condensed layout for the page, but I assume that screens smaller than 640px width are a safe bet.

![artboard 229](https://cloud.githubusercontent.com/assets/15341015/16376446/924bb3f8-3c60-11e6-91e2-29f716ad9080.jpg)

@localgrr: Could you implement these changes?

**Comment by localgrr** [comment]
That dropdown thing isn't going to happen, sorry

**Comment by localgrr** [comment]
And the error, it can only appear above the mobile nav...

**Comment by localgrr** [comment]
![1467037209602screensave](https://cloud.githubusercontent.com/assets/701632/16382913/0fdd07aa-3c83-11e6-869e-a15918e3447e.png)

**Comment by rittermo** [comment]
As discussed: We’ll make a dropdown of the tabs on smaller screens.
