### ISSUE TITLE
inconsistent avatar image urls

### ISSUE THREAD

**Issue by fisx** [liqd/aula#757]
stage1 has image paths `<uid>.png`, but we only store `<uid>.<dim>.png`, so the images are not found.  @np, you said that the default image should not have the `<dim>` tag, and i am leaning towards doing that.

**Comment by fisx** [comment]
> Overview to choose whom to delegate to doesn’t show user avatars
> https://aula-stage1.liqd.net/space/2016-10a/idea/390/delegate

**Comment by fisx** [comment]
> List of delegations has no avatars
> https://aula-stage1.liqd.net/user/18/delegations

**Comment by fisx** [comment]
> List of incoming delegations on topic overview needs padding (avars stuck on the left edge of the container) and user avatars are not shown
> https://aula-stage1.liqd.net/space/school/topic/163/delegations

**Comment by andorp** [comment]
> Overview to choose whom to delegate to doesn’t show user avatars
> https://aula-stage1.liqd.net/space/2016-10a/idea/390/delegate

working


> List of delegations has no avatars
> https://aula-stage1.liqd.net/user/18/delegations

avatars are not shown

>List of incoming delegations on topic overview needs padding (avars stuck on the left edge of the >container) and user avatars are not shown
>https://aula-stage1.liqd.net/space/school/topic/163/delegations

avatars are not shown

**Comment by fisx** [comment]
fixed in #764
