### ISSUE TITLE
Hard coded paths in HTML templates.

### ISSUE THREAD

**Issue by andorp** [liqd/aula#77]
There are similar code snippets in the code base:

````haskell
div_ $ button_ [onclick_ "location.href='/ideas/create'"] "+ Neue Idee"
````

We don't have QA personel to check the page accessibility. Links to pages should not be hard coded in this form. I see two possible solutions:

 * Have one ADT which enumerates all the pages in parallel with the Page types. Which is bad as it leads us to double bookkeeping.
 * Have a type family with type level Strings and use those strings as paths on the value level.

**Comment by fisx** [comment]
yes, this is an issue i hope to find some time thinking about.

related:
- recent off-line conversations with servant people on refactoring servant-client so that it doesn't only give you request generator functions for an api, but also the URI paths.
- https://github.com/haskell-servant/servant/blob/d46cde913c8bcd993c3341b252d2f1f2498211ca/servant/src/Servant/Utils/Links.hs

**Comment by fisx** [comment]
@andorp in the description, you write:

> Links to pages should be hard coded in this form.

Missing a "not"?  Just making sure I understand.

**Comment by fisx** [comment]
> ADT which enumerates all the pages in parallel with the Page types

"maps *paths* to page types"?

**Comment by fisx** [comment]
On a related note, I am concerned that the `RedirectOf` class may be getting us into trouble, too.  It forces us to specify paths based on page types, which makes it hard to move pages around between paths, and forces us to use newtypes if we want to use the same page type twice.  I would prefer to get rid of it and pass it explicitly with the action path.

However, I am excited about the type family idea.  Will think about it some more.

**Comment by fisx** [comment]
The point where type families and paths in type-level string literals gets complicated is in `Capture`-ridden paths.  So this would require not only string-type values, but also function-type values that take capture values and fill them into the wholes in the value string.

Hum, I don't see this working out right now.  Pseudo-code would be appreciated, though.

I will aim for the dict approach.  It requires some manual synchronization work, but all other approaches do that as well, and this has the benefit that all synchronization happens locally in the two routing tables (type level and value level) in one place.

I will give this a shot now.

**Comment by andorp** [comment]
> Missing a "not"? Just making sure I understand.

You are right, I mistyped sorry

**Comment by andorp** [comment]
> "maps paths to page types"?

Not really.

Like:

````haskell
data Pages
  = PLogin PageLogin
  | PCreateIdea PageCreateIdea
  ...               
````

**Comment by andorp** [comment]
> newtypes if we want to use the same page type twice

Separation of concepts: We can reuse the Html template rather than the Page like value and all of its machinery. If two pages are the same for Html and behaviours should be on the same path.

**Comment by andorp** [comment]
> I would prefer to get rid of it and pass it explicitly with the action path.
This could lead us error prone development style. This information should be enforced by the compiler. My reason; lack of QA.

**Comment by andorp** [comment]
> The point where type families and paths in type-level string literals gets complicated is in Capture-ridden paths. 

I dislike the capture based request parameters. Another topic I would like to discuss.

**Comment by andorp** [comment]
Another tought on Capture-ridden paths:

As we are forming the formAction paths from the PageObjects, probably we can do the same with `RedirectOf`. 

````haskell
    formAction (PageCreateTopicAddIdeas topicId _) =
        "/topics/" <> cs (show topicId) <> "/ideas"
````

**Comment by andorp** [comment]
My concern here, as we go towards the HTML related functionality there are less and less checks that the compiler can do for us. On the other hand the client will interact only with the UI and if the UI has broken links, clients get angry easily. That's why I would like to force strong constraints on this topic. If we easy them, we need to write intelligent selenium suites which checks everything for us, and UI based selenium tests are fragile and takes times to run and the feedback loop on an error is long. Which can cause us stronger perturbation and more frustration for the developers.

**Comment by fisx** [comment]
> > "maps paths to page types"?
>
> Not really.
>
> Like:
>
> ````haskell
> data Pages
>   = PLogin PageLogin
>   | PCreateIdea PageCreateIdea
>   ...
> ````

but this is just a list of page types.  where do the actual paths come in?
