### ISSUE TITLE
Change wording of like/quorum button

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#779]
The wording wording of the like/quorum button should be changed to “ "Auf den Tisch” and once I clicked it to “Du willst diese Idee auf den Tisch legen”. The second one for the active button is huge and much too long, but Marina wants it that way.

--

From the pad: 
Wording: "Dafür" / "Du hast für diese Idee gestimmt" bitte unbedingt ändern in "Auf den Tisch" / "Du willst diese Idee auf den Tisch legen"
Ein vollständiges Wording kommt bis zum 05.07.

**Comment by fisx** [comment]
I think "Dafür" only shows in the voting phase, next to "Dagegen".

I have made these changes now.  Before:

![2016-06-30-112948_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/16483829/6a244fcc-3eb6-11e6-8b1d-d1451793e944.png)
![2016-06-30-112952_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/16483837/6fec1a7a-3eb6-11e6-8399-0a42cffa6da1.png)

After:

![2016-06-30-113222_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/16483844/7b309c26-3eb6-11e6-92e2-963ba61c5ba5.png)
![2016-06-30-113225_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/16483850/7ecee428-3eb6-11e6-9487-93c47b627f74.png)

**Comment by fisx** [comment]
closed by accident.

**Comment by fisx** [comment]
just realized the mistake in the last text.  will fix, PR coming up.
