### ISSUE TITLE
Preliminary thoughts on roles and access control

### ISSUE THREAD

**Issue by fisx** [liqd/aula#78]
## class `Page`

I looked at the `Page` class in `Frontend.Core` and would like to propose to remove it.  Two reasons: (1) the two redundant (dual?) predicates and their cyclical dependency are confusing and a source of errors (it not a big one); (2) we don't really use it anywhere except for marking pages as private or public and for testing:

```shell
$ git grep isPrivatePage
src/Frontend/Core.hs:    isPublicPage = not . isPrivatePage
src/Frontend/Core.hs:    isPrivatePage :: p -> Bool
src/Frontend/Core.hs:    isPrivatePage = not . isPublicPage
src/Frontend/Core.hs:    isPrivatePage _ = True
src/Frontend/Page/CreateIdea.hs:  isPrivatePage _ = True
src/Frontend/Page/Overview.hs:    isPrivatePage _ = True
src/Frontend/Page/Topic.hs:  isPrivatePage _ = True
tests/Frontend/PageSpec.hs:        \p -> isPublicPage p `shouldNotBe` isPrivatePage p

14 (0) / git 2016-02-22-mf-api-types ghc 7.10.2 / 09:21:40 mf@lig:~/thentos/aula/aula
$ git grep isPublicPage
src/Frontend/Core.hs:    isPublicPage :: p -> Bool
src/Frontend/Core.hs:    isPublicPage = not . isPrivatePage
src/Frontend/Core.hs:    isPrivatePage = not . isPublicPage
src/Frontend/Core.hs:  | isPublicPage p = PublicFrame p
src/Frontend/Core.hs:    frame = if isPublicPage page then publicPageFrame else pageFrame frameUserHack
src/Frontend/Page/Login.hs:  isPublicPage _ = True
src/Frontend/Page/Static.hs:    isPublicPage _ = True
src/Frontend/Page/Static.hs:    isPublicPage _ = True
tests/Frontend/PageSpec.hs:        \p -> isPublicPage p `shouldNotBe` isPrivatePage p
```

and I don't know what we want to use it for.  But I may have missed something.

## Other changes

Note: we need to distinguish between two things that the 'Role' type does for us: access restriction ("you are not allowed to see this") and content shaping ("if you are an admin, this page looks like this for you").  I am mostly concerned with the latter here, as it is more important for our first demonstrations.

Refactorings:

- ~~Change `Group` to `Role` in module `Types`. (solved in #269)~~
- Change `_userGroups` to `_userRoles`, and type it to `Set Role`.  (Note: every user has exactly one role in each school year, but accumulates roles from previous school years.  Also, I think it's a bad idea to introduce this restriction, and if we really have to we should do it not in the engine, but on the UI.)
- Add a `Set Role` argument to page type constructors.  (We may need roles from previous school years to access old content.)  Like this:

```haskell
data PageEditIdea = PageEditIdea (Set Role) Idea

instance ToHtml PageEditIdea where
    toHtml (PageEditIdea roles idea) = div_ $ do
        when (Admin `elem` roles) $ do
            button_ "block this idea"
        h2_ (idea ^. ideaTitle)
        ...
```

- Pages that look the same for everybody do not need a role set; pages that can be viewed when logged out (login page, imprint, ...) can have a `Maybe (Set Role)`.
- [not sure about this one] we may even be able to redirect to /login from inside the page if we manage to fiddle exceptions into our `HtmlT` stack (possibly related: #65):

```haskell
        unless (Admin `elem` roles) $ do
            throwError $ Redirect "/login"
```

**Comment by fisx** [comment]
Copied from https://github.com/liqd/aula/pull/194#discussion_r55929406:

```haskell
class Authorize a where
    authorizeGet :: ActionM r m => Username -> AulaGetter a -> m ()
    authorizeSet :: ActionM r m => Username -> AulaSetter a -> m ()

getDB getter = do
    user <- currentUser
    authorizeGet user getter
    persisistent $ getDB getter
```

**Comment by fisx** [comment]
Update `Page` class has proven useful for several things, but I still think the `isPrivatePage` should go away once we have authorization in place.

Related: non-existnon-existing pages should not 404 when not logged in, but redirect to /login instead. the current behavior leaks existence info on url paths.  Closing resp. issue #257 as duplicate.

**Comment by fisx** [comment]
moving this to it.2 milestone.  not sure how up to date it is any more, but we do need to do some authorization checks.

**Comment by np** [comment]
I think we can close this issue.

**Comment by fisx** [comment]
agreed.
