### ISSUE TITLE
Optimize the layout of the user profile edit

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#781]
The edit form for changing the user profile needs UI love. 

[will add some details soon]

---

From the pad:

Nutzerprofil bearbeiten https://aula-stage1.liqd.net/user/18/edit
Betrifft nicht Beauftragungen, aber hier ist das Layout noch sehr rudimentär. Jedenfalls in Chrome fehlen Abstände zwischen den Elementen Avatar und Beschreibung zur Übersichtlichkeit.

**Comment by fisx** [comment]
fixed in #776 (merged yesterday, not released yet):

![2016-06-30-121549_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/16484943/70df11d4-3ebc-11e6-8222-22ca5e11648b.png)

(the upload dialog is english because of my browser settings)

**Comment by rittermo** [comment]
Perfect!
