### ISSUE TITLE
Delegation graph: Optimization of navigation between scopes 

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#783]
As discussed:

- there should be an automatic expand when a scope other than „all“ is selected in a scope select list
- there should be an „x“ next to the lowest scope select to close it
- the graph should automatically reload on scope change in the select list
- NTH: the „wild ideas space“ is treated as a topic and the wild ideas are visible when the space was selected in the topic scope select list

---

From the pad:

Beauftragungsnetzwerk https://aula-stage1.liqd.net/delegation/view?scope
Die Buttons "Aufklappen" und "Zuklappen" sind bei der Menüführung unintuitiv. Ich habe 5 Minuten gebraucht, bis ich raus hatte, wie man die Ideenräume eingrenzen kann.   ***Alexa: War bei mir auch so***
Ist es möglich, beide Buttons zu entfernen und die Funktionalität "Aufklappen" automatisch bei anklicken eines Menüpunkts auszuführen?
Dazu ist die erste Dropdown ja überflüssig, weil sie grundsätzlich nur einen Menüpunkt enthält.
Auch "Anzeigen" sollte möglichst automatisch bei der Wahl des Ideenraums erfolgen. Es ist sonst verwirrend und umständlich zu bedienen.

**Comment by fisx** [comment]
this is a duplicate of #690.

**Comment by fisx** [comment]
- Since reload can take several seconds if the graph is too big, I think it's better to only do it on pressing a dedicated button.  Is this negotiable?  (Implementing it would actually be easier, and I'll do it if I am asked to, but I'm stll opposed.)
