### ISSUE TITLE
Delegation graph: Show delegatees of a user after searching by default

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#784]
The network of users delegating to a user should be shown by default not after clicking on the user’s node.

I think you were already working on this, @fisx ?

--- 

From the pad:

Wenn man einen Nutzer sucht, wird zunächst nur der Nutzer alleinstehend angezeigt. Das Netzwerk um ihn sieht man erst, wenn man noch einmal auf ihn klickt. Das ist möglicherweise nicht intuitiv und vermittelt den Eindruck, dass der Nutzer keine Beauftragungen vergibt oder bekommt.

**Comment by rittermo** [comment]
This is about what’s shown after searching for a user name in the delegation graph. Sorry, that was not quite clear from hastily written description.

**Comment by fisx** [comment]
no, that was clear to me.  shouldn't be a big deal to change.

**Comment by fisx** [comment]
should we also indicate if there are hidden edges?  it's sort of already obvious from the voting power and the visible edges, though.

**Comment by fisx** [comment]
i think i know what to do here now.

**Comment by fisx** [comment]
forget all of the above, just two changes:

1. show labels nodes that match login name search.
1. one outbound edge on is shown on click.
