### ISSUE TITLE
stop idle movement of nodes in delegation graph

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#789]
Could we stop the jiggling movement of idle nodes in the delegation graph?

---

From the pad:

***Alexa: Ich finde es in der jetztigen Umsetzung fast unnötig bis störend, dass die Stimmen diese Kaulquappen Struktur haben und sich bewegen***

**Comment by fisx** [comment]
fixed in #790.  that was part of the collision avoidance, and i removed it because it was too slow.
