### ISSUE TITLE
make `...` menu more accessible.

### ISSUE THREAD

**Issue by fisx** [liqd/aula#820]
Button labelled `Optionen` with the same size as user profile buttons.

**Comment by fisx** [comment]
https://github.com/liqd/aula/blob/91f658f9f210695f7071c6cd3c2027eae5dd9858/src/Frontend/Page/Topic.hs#L183

`m-dots` also appears in `Idea.hs`, but I think that's it.

**Comment by fisx** [comment]
@localgrr i've created #888 and assigned it to you.  use `git grep contextMenu` to find the places where the menu entries are listed and rendered, respectively.

admin will see the pages like this:

![2016-07-19-195224_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/16960779/1f9f0796-4deb-11e6-8b55-24b93796cd21.png)

![2016-07-19-195305_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/16960782/24e2bacc-4deb-11e6-881b-7aa13d1e19b7.png)

(note that the text of the hourglass is a bit close to the icon, but that's unrelated to this issue.)

There are two issues:

1. the icons in the `a_` links are out of place.  (the `postLink_` entries look a little better.)
1. some of the icons are missing.  (see FIXMEs.)

**Comment by fisx** [comment]
(you can play with which menu entries are shown by replacing the first part of the tuple with `True` or `False`, depending on whether it should be shown or not.  let me know if you want to do this together.)

**Comment by localgrr** [comment]
![screenshot-localhost 8080 2016-07-21 13-07-00](https://cloud.githubusercontent.com/assets/701632/17097804/a8ce619c-525f-11e6-8309-1838676388fb.png) if it were to be text its a hard to read on this phases. Should I change the bg image ..?

**Comment by localgrr** [comment]
OK as agreed in the meeting going to use a CTA style button
