### ISSUE TITLE
show call to action in empty lists.

### ISSUE THREAD

**Issue by fisx** [liqd/aula#823]
status now: some empty lists of user content show a sentence like "nothing here", some don't.

what we want: all lists that are empty should show a "nothing here" message.  all lists that the user can do something about them being empty should include in that message a call to action with a button that links to the place where they can add content.

**Comment by andorp** [comment]
Some possible locations:

 * space - If the user is admin, please create classes
 * space/2016-5b/ideas - Create ideas
 * space/2016-5b/topic - Create topic if there are ideas
 * space/2016-5b/idea/266/view - No comment, create comment if you can
 * delegation/edit/scope/topic-151 - no users in the scope, only cancel button should be rendered
 * space/2016-5b/topic/151/delegations - no delegations, you can delegate
 * delegation/view?scope=topic-163 - No delegations
 * user/1/ideas - Create wild ideas
 * user/1/delegations/to - you can delegate your vote
 * user/1/delegations/from - you can delegate your vote
 * admin/classes - only create class button
 * admin/users - only create user button
 * admin/user/create - selection should not contain student creation if there is no class in the db
