### ISSUE TITLE
meaning of buttons "delegate on * level" in own user profile

### ISSUE THREAD

**Issue by fisx** [liqd/aula#828]
if I visit my own profile, I should see different delegation buttons than on other profiles:

- label should be "meine stimme für klasse 8c beautragen" ("delegate my vote for class 8c").
- leads to `PageDelegateVote`, listing all potential delegates in class 8c.
- analogously for all idea spaces i'm in.

**Comment by andorp** [comment]
The text has not changed on the buttons. The rest is implemented in #841.

**Comment by fisx** [comment]
i guess this should be assigned to me?
