### ISSUE TITLE
Redirect 303 to page that redirects to "Your something has created" page that redirects too.

### ISSUE THREAD

**Issue by andorp** [liqd/aula#83]
From https://github.com/liqd/aula/pull/56#issuecomment-185281700 :

> This should probably go to some US page, but let me just write it down here: On saving a newly created topic, we will probably have to show a page saying "your topic has been created", which redirects on button click or with a delay of 3 seconds.

We have to implement this requirement to avoid the [Double Submit problem](http://www.theserverside.com/news/1365146/Redirect-After-Post) which occurs when there is no redirect 303 after POST requests. We need to create (lets call) ACK pages, but in the following way:

For example:

 1. GET request on "/ideas/create"
 2. User adds content, submits POST
 3. POST request on "/ideas/create"
 4. Redirect 303 to "/ideas/create-ack"
 5. User's browser renders the ACK page which redirects to "/ideas" page after 3 seconds (redirect in HTML header)

**Comment by andorp** [comment]
The Mantra
    
    PRG pattern can be rephrased like this:
    
        Never show pages in response to POST
        Always load pages using GET
        Navigate from POST to GET using REDIRECT

**Comment by np** [comment]
Could redirect directly to "/ideas" but with a small banner message saying "Your idea has been created".

**Comment by fisx** [comment]
I guess the idea is that if you show the post page even for three seconds, the user can try to reload it, and will thus repost.

This is more of a usability issue: with @andorp's way, the user will never have to deal with annoying browser popups saying that reload is not recommended in this situation.

**Comment by andorp** [comment]
The problem is that we have an exact requirement on this. At least we had last week.

**Comment by andorp** [comment]
@fisx: It not just a usability issue. If we allow such behaviour, users will do repost, and we had to come up some logic which has a heuristic on data similarity as a change request from the client. __We do not want to go that direction__ believe me.

**Comment by andorp** [comment]
The redirection page from the old click dummy: https://marvelapp.com/ehhb43#10293398
The new does not have it, but I don't know the actual requirement set.

**Comment by np** [comment]
I didn't meant to show the post page but to redirect. However instead of redirecting twice, I suggest to redirect only once.

**Comment by andorp** [comment]
@np. I got it, and this is the way it works now. But as far as I know that contradicts for the actual requirement set we have.

**Comment by fisx** [comment]
> @fisx: It not just a usability issue. If we allow such behaviour, users will do repost, and we had to come up some logic which has a heuristic on data similarity as a change request from the client. __We do not want to go that direction__ believe me.

but we can't have aula's security depend on users not doing re-posts, even with your trick!  a malevolent user can always construct a post request manually and send it more than once.

or did i get you wrong?

**Comment by fisx** [comment]
> @np. I got it, and this is the way it works now. But as far as I know that contradicts for the actual requirement set we have.

that's also my most recent info: the user will click on 'safe', then see a page: "you have saved!" for three seconds, then be redirected to "/ideas".  i would like to work with that hypothesis and change it to the simpler thing on change request only.

**Comment by andorp** [comment]
> malevolent

That's True.

But the double `submit problem` can come from slow and broken connections. 

My point is here
 * avoid `double submit` and fulfil the requirement with ack pages OR
 * avoid `double submit` and change requirements not to have ack pages

**Comment by andorp** [comment]
> that's also my most recent info: the user will click on 'safe', then see a page: "you have saved!"

The "you have saved!" is the ACK page in my description.

**Comment by rittermo** [comment]
Hi everyone! @andorp just directed me to your discussion here. 

I just wanted to point out that is not a requirement to have a separate page for these kinds of status messages. The way I see them – and hopefully our designer does too – is that they are just giant versions of these little status messages that you see in UIs a lot. As an example: In my understanding, a user who added an idea could be redirected to the view of his/her idea and then the confirmation is shown as an overlay for a second or two on that page. There would be no need for another redirect. There would only be a need for some kind of trigger for Caroline – maybe via some session cookie?–, so she knows when to show which overlay.

Also, this is not an essential feature for our prototype. It is completely fine if these confirmation messages are not shown or shown in a different way until the middle of June.

**Comment by andorp** [comment]
@rittermo  That's a big relief.

**Comment by fisx** [comment]
thanks rittermo.  that helped clarify things!

@andorp's original point is still valid though that the post target page should always be just a redirect and not show any Html, whether temporarily or not.

**Comment by fisx** [comment]
Just thought of something.  Is the conclusion of this conversation that we *only* have redirecting forms?  That would make the api of the servant-df considerably simpler!

**Comment by np** [comment]
Can we close this now?
