### ISSUE TITLE
Shorter profile texts

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#855]
https://aula-stage2.liqd.net/user/10/ideas
Demo data for profile texts should only be max two paragraphs / 500 characters

**Comment by fisx** [comment]
it's not a big deal to do this, but how important is it?  we won't have demo content in production mode anyway.

also note that there are other consistency issues with the demo content that i'd consider more serious (like users creating ideas in idea spaces they don't have access to.)

**Comment by fisx** [comment]
closing, as just discussed.
