### ISSUE TITLE
indicate the phase an idea is in

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#861]
Currently we don’t show which phase an idea is in on the idea detail page.
We should show the title of the phase above the idea title
We should evaluate if we can use the color of the phase header image to indicate which phase the idea is in

**Comment by rittermo** [comment]
I will discuss this with Nadine first.

**Comment by fisx** [comment]
actually, we do indicate the phase:

![2016-07-20-142924_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/16986379/834a5692-4e86-11e6-8a54-e9f241007f60.png)

but it's true that the indication is very subtle.

**Comment by fisx** [comment]
topic overview works, idea overview doesn't.  i'm going to look into this.
