### ISSUE TITLE
change the timestamp’s format for refinement and voting phase

### ISSUE THREAD

**Issue by rittermo** [liqd/aula#865]
The timestamp that indicates the end date of refinement phase and voting phase on the topic overview page should be changed:
- It should use the German date format dd.mm.YYYY 
- the timezone’s name should be removed

**Comment by fisx** [comment]
no time of day?  (it's not a problem to do that, but i'd be confused if i were a user and didn't get that information out of the time stamp.)

**Comment by fisx** [comment]
as discussed, we keep the hour (turns out we didn't do minutes until now either):

![2016-07-20-142552_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/16986291/eea0da02-4e85-11e6-97fd-d134f2371d0d.png)

pull request coming up!
