### ISSUE TITLE
unapplicable tabs are still shown in user profile

### ISSUE THREAD

**Issue by fisx** [liqd/aula#912]
e.g. admin user profile: there shouldn't be any tabs, but two of the three tabs headings are still there.

(if this is due to the fact that admin is god, please close this.)

![2016-07-25-120540_1600x900_scrot](https://cloud.githubusercontent.com/assets/10210727/17100344/0dc1cae0-526e-11e6-864b-54720597ea06.png)

**Comment by andorp** [comment]
With god-admin turned off:
![2016-07-25-202745_1600x900_scrot](https://cloud.githubusercontent.com/assets/3465327/17112446/623b0f36-52a6-11e6-9a1d-79c9fd6caab8.png)

**Comment by fisx** [comment]
sorry...

i the idea just occurred to me when i had more or less sent the issue already.

(but why are the tabs there and not the contents?)
