### ISSUE TITLE
make the location of avatar images configurable via aula.yaml

### ISSUE THREAD

**Issue by fisx** [liqd/aula#925]
this is needed for the test suite to have its own location for avatar
images.

we already use a temp file in tests here:
https://github.com/liqd/aula/blob/31d32df18871a465cbc9a16d50df635555484eb4/tests/Frontend/Page/AdminSpec.hs#L69

https://hackage.haskell.org/package/temporary-1.2.0.4/docs/System-IO-Temp.html
also has something for creating directories.

i think the biggest challenge with this will be that we need the
config in lots of places deep in some pure computations where we have
to pass it down by hand.

while we're at it, we might as well look what bits and pieces of
persistent state we are not mentioning in aula.yaml yet, and add them.
here is another list, from a whiteboard session this morning.  is it
complete?:

- acid-state
- avatar images
- /static
- event log
- system log (?)
- aula.yaml

**Comment by andorp** [comment]
I think the list is complete.

**Comment by andorp** [comment]
Fixed in #931
