### ISSUE TITLE
Menu burger button not visible anymore.

### ISSUE THREAD

**Issue by vellip** [liqd/aula#980]
This change https://github.com/liqd/aula/commit/e295cacbdcbae53e70e7a23bc8855157aa08b4cb made the burger button stay hidden on the phone breakpoint, regardless of whether the user is logged in or not.

This is because the `#mobile-menu-button` got moved into the `. main-header-user` which is `display: none` all the time, hiding it and it's descendants. Maybe a solution would be to undo the change and make the menu markup simply not be output when not logged in.

**Comment by fisx** [comment]
Hi @vellip.  Thanks for the quick response, I will take a look at your suggestion.

**Comment by fisx** [comment]
I essentially did what you suggested in #981, which solves it on the first random android phone I could get my hands on.  Thanks again, problem solved!
