### ISSUE TITLE
password reset emails are not sent

### ISSUE THREAD

**Issue by fisx** [liqd/aula#988]
i have a user with a registered email address, and am not logged in.  i click on 'send password reset token' and enter my email address and submit the form.

expected:
- log file shows that an email is sent.
- i receive an email.

actual behavior:
- neither.

**Comment by fisx** [comment]
(observed on demo1.aula.de, which is currently set to my email.  also observed on other production machines.)

**Comment by fisx** [comment]
correction: email is sent!  no log file entry, but that may be desired behavior.

so this is probably gmail having a picky spam filter.  :-(

not sure where to take this from here...

**Comment by andorp** [comment]
Sending emails should be logged in my opinion, it is a useful information for debugging.

**Comment by fisx** [comment]
We could always look into `/var/log/mail.info`, though.

**Comment by fisx** [comment]
ok, i'm closing this:

- logging is covered by postfix
- emails (password reset emails in particular) have been received by other addresses
- user has been asked to check spam folder(s) and wait a few hours

*if* this remains an issue it's not one of the aula code base, but of negotiating spam detection between aula postfix and gmail.

**Comment by andorp** [comment]
> We could always look into /var/log/mail.info, though.

Good enough
