### ISSUE TITLE
students can delete comments of others

### ISSUE THREAD

**Issue by fisx** [liqd/aula#989]

**Comment by fisx** [comment]
(also, please add a test case.  does not matter on which layer (action or selenium or whatnot).

**Comment by andorp** [comment]
I couldn't reproduce it.

**Comment by andorp** [comment]
Steps:
1. Login with student A in class C
2. Place a comment on school level idea
3. Logout
4. Login with student B in class C
5. Try to delete the comment which was placed by student A

**Comment by andorp** [comment]
If the user has multiple roles, like moderator and student. The user can do both things like the moderator and the student.

**Comment by andorp** [comment]
* A selenium test case would be appropiate to automate this. We lack of such framework.
 * At `Action` level the deletion of comments are not restricted. Writing tests their would produce a false negative.

**Comment by fisx** [comment]
please re-open if more information is available on this.
