### ISSUE TITLE
user profile tabs: "delegateTo" and "delegateFrom" labels are flipped.

### ISSUE THREAD

**Issue by fisx** [liqd/aula#991]

**Comment by andorp** [comment]
I checked this. for me seems the tabs are right...

**Comment by andorp** [comment]
Probably the URL is missleading...
![2016-10-18-125635_1600x900_scrot](https://cloud.githubusercontent.com/assets/3465327/19475077/91dd6d8c-9532-11e6-9c0f-9305d8a23e65.png)

**Comment by andorp** [comment]
We can ask poly to provide an URL if the issue persist on their side.

**Comment by fisx** [comment]
i'm also confused, so we should probably add a comment to the source like this:

- delegatees give their vote to me, so i vote for them: "für wen stimme ich ab?" ("for whom do i vote?")
- delegates get their vote from me, so they vote for me: "wer stimmt für mich ab?" ("who votes for me?")
